version: '3.8'
services:

  america-market:
    image: banitsa/market
    ports:
      - 7091:7091
    environment:
      JAVA_TOOL_OPTIONS: '-Dcom.sun.management.config.file=data/management.properties
                          -Dcom.sun.management.jmxremote.port=7091
                          -Dcom.sun.management.jmxremote.rmi.port=7091
                          -Djava.rmi.server.hostname=ecsc00a08208
                          -Dspring.profiles.active=America'
    volumes:
      - type: "bind"
        source: "data"
        target: "/workspace/data"
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  asia-market:
    image: banitsa/market
    ports:
      - 7092:7092
    environment:
      JAVA_TOOL_OPTIONS: '-Dcom.sun.management.config.file=data/management.properties
                          -Dcom.sun.management.jmxremote.port=7092
                          -Dcom.sun.management.jmxremote.rmi.port=7092
                          -Djava.rmi.server.hostname=ecsc00a08208
                          -Dspring.profiles.active=Asia'
    volumes:
      - type: "bind"
        source: "data"
        target: "/workspace/data"
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  europe-market:
    image: banitsa/market
    ports:
      - 7093:7093
    environment:
      JAVA_TOOL_OPTIONS: '-Dcom.sun.management.config.file=data/management.properties
                          -Dcom.sun.management.jmxremote.port=7093
                          -Dcom.sun.management.jmxremote.rmi.port=7093
                          -Djava.rmi.server.hostname=ecsc00a08208
                          -Dspring.profiles.active=Europe'
    volumes:
      - type: "bind"
        source: "data"
        target: "/workspace/data"
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

#  aurora:
#    image: banitsa/aurora
#    environment:
#      SPRING_APPLICATION_JSON: '{ "grpc.channel.host": "europe-market", "grpc.channel.port": "8082" }'
#    deploy:
#      placement:
#        constraints: [node.labels.purpose == general-purpose]
#
#  orderbook:
#    image: banitsa/orderbook
#    deploy:
#      placement:
#        constraints: [node.labels.purpose == general-purpose]

  calculator:
    image: banitsa/calculator
    ports:
      - 80:8080
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  dozzle:
    image: amir20/dozzle:v2.1.1
    volumes:
      - type: "bind"
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
    ports:
      - 9999:8080
    deploy:
      placement:
        constraints: [node.role == manager]

  web:
    image: nginx:1.19
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - type: "bind"
        source: "data"
        target: "/usr/share/nginx/html"
    ports:
      - 9000:80
    deploy:
      placement:
        constraints: [node.role == manager]