version: '3.8'
services:

  america-market:
    image: banitsa/market
    ports:
      - 7091:7091 # for jmx
      - 8081:8081 # for grpc
    environment:
      JAVA_TOOL_OPTIONS: '-Dcom.sun.management.config.file=data/management.properties
                          -Dcom.sun.management.jmxremote.port=7091
                          -Dcom.sun.management.jmxremote.rmi.port=7091
                          -Djava.rmi.server.hostname=ecsc00a08208
                          -Dspring.profiles.active=America'
    volumes:
      - type: "bind"
        source: "data"
        target: "/workspace/data"
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  asia-market:
    image: banitsa/market
    ports:
      - 7092:7092 # for jmx
      - 8082:8082 # for grpc
    environment:
      JAVA_TOOL_OPTIONS: '-Dcom.sun.management.config.file=data/management.properties
                          -Dcom.sun.management.jmxremote.port=7092
                          -Dcom.sun.management.jmxremote.rmi.port=7092
                          -Djava.rmi.server.hostname=ecsc00a08208
                          -Dspring.profiles.active=Asia'
    volumes:
      - type: "bind"
        source: "data"
        target: "/workspace/data"
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  europe-market:
    image: banitsa/market
    ports:
      - 7093:7093 # for jmx
      - 8083:8083 # for grpc
    environment:
      JAVA_TOOL_OPTIONS: '-Dcom.sun.management.config.file=data/management.properties
                          -Dcom.sun.management.jmxremote.port=7093
                          -Dcom.sun.management.jmxremote.rmi.port=7093
                          -Djava.rmi.server.hostname=ecsc00a08208
                          -Dspring.profiles.active=Europe'
    volumes:
      - type: "bind"
        source: "data"
        target: "/workspace/data"
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  aurora:
    image: banitsa/aurora
    ports:
      - 7094:7094 # for jmx
      - 8084:8084 # for grpc
    environment:
      JAVA_TOOL_OPTIONS: '-Dcom.sun.management.config.file=data/management.properties
                          -Dcom.sun.management.jmxremote.port=7094
                          -Dcom.sun.management.jmxremote.rmi.port=7094
                          -Djava.rmi.server.hostname=ecsc00a08208
                          -Dorderbook.grpc.server.host=orderbook'
    volumes:
      - type: "bind"
        source: "data"
        target: "/workspace/data"
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  orderbook:
    image: banitsa/orderbook
    ports:
      - 7095:7095 # for jmx
      - 8085:8085 # for grpc
    environment:
      JAVA_TOOL_OPTIONS: '-Dcom.sun.management.config.file=data/management.properties
                          -Dcom.sun.management.jmxremote.port=7095
                          -Dcom.sun.management.jmxremote.rmi.port=7095
                          -Djava.rmi.server.hostname=ecsc00a08208'
    volumes:
      - type: "bind"
        source: "data"
        target: "/workspace/data"
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  calculator:
    image: banitsa/calculator
    ports:
      - 7096:7096 # for jmx
      - 8086:8086 # for grpc
      - 8080:8080   # for http
    environment:
      JAVA_TOOL_OPTIONS: '-Dcom.sun.management.config.file=data/management.properties
                          -Dcom.sun.management.jmxremote.port=7096
                          -Dcom.sun.management.jmxremote.rmi.port=7096
                          -Djava.rmi.server.hostname=ecsc00a08208'
    volumes:
      - type: "bind"
        source: "data"
        target: "/workspace/data"
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  webapp:
    image: banitsa/webapp
    ports:
      - 80:80
    environment:
      - "CALCULATOR_SERVICE_URL=http://ecsc00a08208:9090"
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  envoy-proxy:
    image: banitsa/envoy-proxy:latest
    ports:
      - 9090:9090
      - 9901:9901
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  persist:
    image: banitsa/persist
    ports:
      - 7097:7097 # for jmx
    environment:
      JAVA_TOOL_OPTIONS: '-Dcom.sun.management.config.file=data/management.properties
                          -Dcom.sun.management.jmxremote.port=7097
                          -Dcom.sun.management.jmxremote.rmi.port=7097
                          -Djava.rmi.server.hostname=ecsc00a08208
                          -Dspring.datasource.url=jdbc:postgresql://10.6.17.88:5432/banica'
    volumes:
      - type: "bind"
        source: "data"
        target: "/workspace/data"
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  dozzle:
    image: amir20/dozzle:v2.1.1
    volumes:
      - type: "bind"
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
    ports:
      - 9999:8080
    deploy:
      placement:
        constraints: [node.role == manager]

  web:
    image: nginx:1.19
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - type: "bind"
        source: "data"
        target: "/usr/share/nginx/html"
    ports:
      - 9000:80
    deploy:
      placement:
        constraints: [node.role == manager]